### ISSUE TITLE
focus functional purpose

### ISSUE THREAD

**Issue by mlp6** [haleyelena/474-Project#1]
https://github.com/haleyelena/474-Project/blob/ae88cd4a6fbf0637d070b00f6a81fcc9d6282f67/mainprogram.py#L108

It would be good practice to create a dedicated function that would read data from the serial data stream and validate it to then use in other functions instead of embedding it into a primarily plotting function.

**Comment by haleyelena** [comment]
Got it, will do asap. Also will add docstrings to all functions :)
