### ISSUE TITLE
add rhyme/reason to value 100

### ISSUE THREAD

**Issue by mlp6** [haleyelena/474-Project#2]
https://github.com/haleyelena/474-Project/blob/9b3a56a5503b8d9ad458563064d1db433683b13e/version1.py#L161

unclear what dictates this value; maybe pull out as a constant defined that could be adjusted and the algorithm could have less hard-coded values and be dependent on the variable value

**Comment by haleyelena** [comment]
i just picked it because it only dictates how much serial monitor data is showing at a time

**Comment by haleyelena** [comment]
But so I'm not sure when/why it would need to be changed but i can make it a variable anyway just for better practice!

**Comment by mlp6** [comment]
Is it just for debugging purposes?  If so, then maybe you can wrap such content and flag "on" when debugging.  Makes it clear to someone reading your code.  ;)
