### ISSUE TITLE
does `value` need to be a float (int/int math)

### ISSUE THREAD

**Issue by mlp6** [haleyelena/474-Project#3]
https://github.com/haleyelena/474-Project/blob/ecff1546d38c5792498bf06478621d1422a803a1/MedRhythmsArduino.ino#L202

**Comment by ral32** [comment]
The value will be an int from 1-5 since we will be outputting levels rather than exact measurements.

**Comment by mlp6** [comment]
@ral32 but can the math be done correctly if the result of the division is a floating point number (you can then typecast it to an int, or you can do something like:

`value = int(WindSpeed_MPH / range_in);`

**Comment by ral32** [comment]
Oh, I see. We will fix that.
